### ISSUE TITLE
unittests failing on python 3.13

### ISSUE THREAD

**Issue by jmw182** [pitt-rnel/pyrtma#28]
test_reserve_syntax fails on python 3.13, but running the message compiler appears to work as expected.

The output of run_tests.sh is pasted below:

```
======================================================================
ERROR: test_reserve_syntax (tests.test_parser.TestParser.test_reserve_syntax)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\git\climber_root\components\rtma\pyrtma\tests\test_parser.py", line 632, in test_reserve_syntax
    self.parser.parse(self.tmp.path)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\git\climber_root\components\rtma\pyrtma\src\pyrtma\parser.py", line 1353, in parse
    self.parse_file(defs_path)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\git\climber_root\components\rtma\pyrtma\src\pyrtma\parser.py", line 1392, in parse_file
    self.parse_text(text)
    ~~~~~~~~~~~~~~~^^^^^^
  File "C:\git\climber_root\components\rtma\pyrtma\src\pyrtma\parser.py", line 1307, in parse_text
    self.handle_message_def(name, mdf)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\git\climber_root\components\rtma\pyrtma\src\pyrtma\parser.py", line 1123, in handle_message_def
    raise InvalidTypeError(
        f"Invalid object type for message def {name} of {type(mdf).__name__} -> {self.current_file}"
    )
pyrtma.parser.InvalidTypeError: Invalid object type for message def _RESERVED_ of list -> C:\Users\jmw182\AppData\Local\Temp\tmpnn4g98gm.yaml

----------------------------------------------------------------------
Ran 57 tests in 24.962s

FAILED (errors=1)
```

**Comment by jmw182** [comment]
Fixed in e0e7800
